name: task2
description: JsonSerialization Builder
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  source_gen: ^4.0.2
  analyzer: ^8.3.0
  build: ^4.0.2
  duration: ^4.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
