name: task1
description: Builder that generates a summary file with the number of lines in each Dart file.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  build: ^4.0.2
  glob: ^2.1.3
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
